language: R
cache: packages

env:
  global:
    - secure: A_LONG_ENCRYPTED_STRING

install:
  - echo "install"
  - ls -la .
  - which env
      
script:
  - ./.travis-build.sh

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $BOOK_GHP_UPLOAD_KEY
  keep_history: true
  local_dir: .
  on:
    branch: master
