language: R
cache: packages

env:
  global:
    - secure: A_LONG_ENCRYPTED_STRING

install:
  - sudo apt-get update
  - sudo apt-get install -y --no-install-recommends 
    latexmk
    freeglut3
  - tlmgr install asymptote pxfonts babel-estonian bbm economic
  - Rscript -e "install.packages(c('knitr', 'ggplot2', 'dplyr'))"

script:
  - ./.travis-build.sh

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $MATH_CHEATSHEET_KEY
  keep_history: true
  local_dir: .
  on:
    branch: master
