language: R
cache: packages

env:
  global:
    - secure: A_LONG_ENCRYPTED_STRING

install:
  - echo "install"
  - ls -la .
  - Rscript -e "install.packages(c('knitr'))"

script:
  - ./.travis-build.sh

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $MATH_CHEATSHEET_KEY
  keep_history: true
  local_dir: .
  on:
    branch: master
